# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.
# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  link_right_arm_0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
  link_right_arm_1:
    - "center": [-0.05, -0.01, 0.02]
      "radius": 0.05
    - "center": [-0.0, -0.01, -0.05]
      "radius": 0.04
    - "center": [0.02, -0.01, 0.02]
      "radius": 0.05
  link_right_arm_2:
    - "center": [0.0, 0.0, -0.14]
      "radius": 0.05
    - "center": [0.0, 0.0, -0.2]
      "radius": 0.05
    - "center": [-0.016, 0.0, -0.22]
      "radius": 0.04
  link_right_arm_3:
    - "center": [0.0, 0.03, 0.0]
      "radius": 0.04
    - "center": [-0.03, 0.0, -0.08]
      "radius": 0.04
    - "center": [-0.03, 0.0, -0.12]
      "radius": 0.04
    - "center": [0.0, -0.03, 0.0]
      "radius": 0.04
  link_right_arm_4:
    - "center": [0.0, -0.04, 0.03]
      "radius": 0.025
    - "center": [0.0, -0.04, 0.0]
      "radius": 0.02
    - "center": [0.0, -0.04, 0.07]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.1]
      "radius": 0.02
  link_right_arm_5:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.04
    - "center": [0.0, 0.03, 0.0]
      "radius": 0.04
    - "center": [0.0, 0.0, -0.05]
      "radius": 0.04
    - "center": [0.0, -0.013, 0.0]
      "radius": 0.04
  link_right_arm_6:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.001
  FT_sensor_R:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.04
  ee_right:
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.03
    - "center": [0.0, 0.0, -0.045]
      "radius": 0.03
    - "center": [-0.03, 0.0, -0.045]
      "radius": 0.03
    - "center": [0.03, 0.0, -0.045]
      "radius": 0.03
  ee_finger_r1:
    - "center": [0.0, 0.0, -0.05]
      "radius": 0.01
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.01
  ee_finger_r2:
    - "center": [0.0, 0.0, -0.05]
      "radius": 0.01
    - "center": [0.0, 0.0, -0.02]
      "radius": 0.01
