#!/usr/bin/env python3
"""Stage the locally available research assets for a repeatable three-robot kitchen run.

All files remain in their source trees. The stage is a writable directory of file symlinks,
except for the generated AI Worker planning URDF and new kitchen outputs. It is intentionally
kept under outputs/ by default and must not be included in a public source archive.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
LOCK = REPO / "docs/research-asset-lock.json"
AIWORKER_SOURCE = Path(
    "ffw_description/urdf/ffw_bg2_rev5_follower/ffw_bg2_follower.urdf"
)
AIWORKER_TARGET = Path(
    "ffw_description/urdf/ffw_sg2_follower/ffw_sg2_follower.urdf"
)
RBY1_ROOT_USD = Path("models/rby1m/urdf/model/model_simvla_black_gripper.usd")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_lock(roots: dict[str, Path], lock: dict) -> None:
    """Check pinned identity before creating an output directory."""
    for name, expected in lock["sha256"].items():
        section, relative = name.split("/", 1)
        path = roots[section] / relative
        if not path.is_file():
            raise ValueError(f"missing pinned asset {name}: {path}")
        actual = sha256(path)
        if actual != expected:
            raise ValueError(
                f"asset checksum mismatch for {name}: expected {expected}, found {actual}"
            )


def repository_head(root: Path) -> str:
    """Return the checked-out Git revision for an asset source tree."""
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise ValueError(f"asset source is not a readable Git checkout: {root}") from exc
    return result.stdout.strip()


def verify_revisions(source: Path, rby1: Path, lock: dict) -> dict[str, str]:
    """Verify source revisions as well as the individual asset hashes."""
    actual = {
        "source_commit": repository_head(source),
        "rby1_source_commit": repository_head(rby1),
    }
    for key, revision in actual.items():
        expected = lock.get(key)
        if not expected:
            raise ValueError(f"asset lock is missing {key}")
        if revision != expected:
            raise ValueError(
                f"asset source revision mismatch for {key}: expected {expected}, found {revision}"
            )
    return actual


def usd_tool_environment(usd_python: Path) -> dict[str, str]:
    """Expose usd-core's bundled shared libraries to its plugin loader."""
    environment = os.environ.copy()
    result = subprocess.run(
        [str(usd_python), "-c", "import sysconfig; print(sysconfig.get_paths()['purelib'])"],
        check=True,
        capture_output=True,
        text=True,
    )
    libraries = Path(result.stdout.strip()) / "usd_core.libs"
    if libraries.is_dir():
        existing = environment.get("LD_LIBRARY_PATH", "")
        environment["LD_LIBRARY_PATH"] = str(libraries) + (f":{existing}" if existing else "")
    return environment


def link_tree(source: Path, target: Path, *, skip: set[Path] | None = None) -> int:
    """Mirror regular files as symlinks while keeping directories writable."""
    skip = skip or set()
    count = 0
    for current, dirs, files in os.walk(source):
        here = Path(current)
        relative = here.relative_to(source)
        destination = target / relative
        destination.mkdir(parents=True, exist_ok=True)
        dirs[:] = [name for name in dirs if name not in {"__pycache__", ".git"}]
        for name in files:
            if name.startswith(".nfs"):
                continue
            src = here / name
            rel = relative / name
            if rel in skip:
                continue
            if not src.is_file():
                raise ValueError(f"unsupported asset entry: {src}")
            (destination / name).symlink_to(src.resolve())
            count += 1
    return count


def env_text(stage: Path, bodex: Path | None) -> str:
    settings = {
        "SIMVLA_REPO_ROOT": REPO,
        "SIMVLA_ASSETS_DIR": stage / "assets",
        "SIMVLA_ROBOT_MODELS_DIR": stage / "models",
        "SIMVLA_RBY1M_DIR": stage / "rby1m",
        "SIMVLA_GOALS_DIR": REPO / "examples/goals",
        "SIMVLA_LEROBOT_ROOT": REPO / "outputs/lerobot",
    }
    if bodex is not None:
        settings["BODEX_OBJ_DIR"] = bodex
    return "# Generated by scripts/tools/stage_research_assets.py\n" + "".join(
        f"export {name}={shlex.quote(str(value))}\n" for name, value in settings.items()
    )


def verify_stage(
    output: Path,
    source: Path,
    rby1: Path,
    bodex: Path | None,
    lock: dict,
    revisions: dict[str, str],
) -> dict:
    manifest_path = output / "manifest.json"
    if not manifest_path.is_file():
        raise ValueError(f"existing stage lacks manifest.json: {output}")
    manifest = json.loads(manifest_path.read_text())
    if (manifest.get("source_root"), manifest.get("rby1_root"), manifest.get("bodex_root")) != (
        str(source), str(rby1), str(bodex) if bodex is not None else None
    ):
        raise ValueError(f"existing stage was made from different source roots: {output}")
    if manifest.get("source_commit") != revisions["source_commit"]:
        raise ValueError(f"existing stage was made from different source revisions: {output}")
    if manifest.get("rby1_source_commit") not in (None, revisions["rby1_source_commit"]):
        raise ValueError(f"existing stage was made from a different RB-Y1 revision: {output}")
    prior_hashes = manifest.get("sha256", {})
    if (any(lock["sha256"].get(name) != value for name, value in prior_hashes.items()) or
            manifest.get("generated_aiworker_urdf_sha256") !=
            lock["generated_aiworker_urdf_sha256"] or
            manifest.get("relativized_rby1_usd_sha256") !=
            lock.get("relativized_rby1_usd_sha256")):
        raise ValueError(f"existing stage uses a different asset lock: {output}")
    generated = output / "models/ai_worker_min" / AIWORKER_TARGET
    if not generated.is_file() or sha256(generated) != manifest.get("generated_aiworker_urdf_sha256"):
        raise ValueError(f"generated AI Worker URDF is missing or changed: {generated}")
    portable_usd = output / "rby1m" / RBY1_ROOT_USD
    if not portable_usd.is_file() or sha256(portable_usd) != lock["relativized_rby1_usd_sha256"]:
        raise ValueError(f"portable RB-Y1 USD is missing or changed: {portable_usd}")
    if (output / "env.sh").read_text() != env_text(output, bodex):
        raise ValueError(f"existing stage has a changed environment file: {output / 'env.sh'}")
    linked_roots = {
        "assets": (output / "assets", source / "source/isaaclab_assets/data"),
        "anubis": (output / "models/anubis", source / "anubis"),
        "aiworker": (output / "models/ai_worker_min", source / "ai_worker_min"),
        "rby1m": (output / "rby1m", rby1),
    }
    for section, expected_count in manifest["links"].items():
        root = output / {
            "assets": "assets",
            "anubis": "models/anubis",
            "aiworker": "models/ai_worker_min",
            "rby1m": "rby1m",
        }[section]
        links = [path for path in root.rglob("*") if path.is_symlink()]
        if section == "rby1m":
            links = [path for path in links if path.relative_to(output / "rby1m") != RBY1_ROOT_USD]
        expected_source = linked_roots[section][1].resolve()
        if (len(links) != expected_count or any(not path.is_file() for path in links) or
                any(expected_source not in path.resolve().parents for path in links)):
            raise ValueError(f"missing or broken source links under {root}")
    if (manifest.get("sha256") != lock["sha256"] or
            any(manifest.get(key) != value for key, value in revisions.items())):
        manifest["sha256"] = lock["sha256"]
        manifest.update(revisions)
        manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


def stage(
    source: Path,
    rby1: Path,
    output: Path,
    bodex: Path | None = None,
    usd_python: Path = Path(sys.executable),
) -> dict:
    source, rby1, output = source.resolve(), rby1.resolve(), output.resolve()
    if output == source or source in output.parents or output == rby1 or rby1 in output.parents:
        raise ValueError("stage output must be outside both source trees")
    roots = {
        "assets": source / "source/isaaclab_assets/data",
        "models": source,
        "rby1m": rby1,
    }
    lock = json.loads(LOCK.read_text())
    revisions = verify_revisions(source, rby1, lock)
    verify_lock(roots, lock)
    if bodex is not None:
        bodex = bodex.resolve()
        if not (bodex / "use_data").is_dir() or not (bodex / "graspdata_final").is_dir():
            raise ValueError(f"BODex root needs use_data/ and graspdata_final/: {bodex}")
    if output.exists():
        return verify_stage(output, source, rby1, bodex, lock, revisions)
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=f".{output.name}-", dir=output.parent) as temporary:
        work = Path(temporary)
        counts = {
            "assets": link_tree(roots["assets"], work / "assets"),
            "anubis": link_tree(source / "anubis", work / "models/anubis"),
            "aiworker": link_tree(
                source / "ai_worker_min", work / "models/ai_worker_min",
                skip={AIWORKER_TARGET},
            ),
            "rby1m": link_tree(rby1, work / "rby1m"),
        }
        counts["rby1m"] -= 1
        source_rby_usd = work / "rby1m" / RBY1_ROOT_USD
        source_rby_usd.unlink()
        subprocess.run(
            [str(usd_python), str(REPO / "scripts/tools/relativize_rby1_usd.py"),
             "--source", str(rby1 / RBY1_ROOT_USD), "--output", str(source_rby_usd)],
            check=True,
            env=usd_tool_environment(usd_python),
        )
        portable_usd_hash = sha256(source_rby_usd)
        if portable_usd_hash != lock["relativized_rby1_usd_sha256"]:
            raise ValueError(
                f"RB-Y1 USD normalizer produced {portable_usd_hash}; expected "
                f"{lock['relativized_rby1_usd_sha256']}"
            )
        subprocess.run(
            [sys.executable, str(REPO / "scripts/tools/build_aiworker_urdf.py"),
             "--source", str(work / "models/ai_worker_min" / AIWORKER_SOURCE),
             "--output", str(work / "models/ai_worker_min" / AIWORKER_TARGET)],
            check=True,
        )
        generated = work / "models/ai_worker_min" / AIWORKER_TARGET
        generated_hash = sha256(generated)
        if generated_hash != lock["generated_aiworker_urdf_sha256"]:
            raise ValueError(
                f"AI Worker URDF builder produced {generated_hash}; expected "
                f"{lock['generated_aiworker_urdf_sha256']}"
            )
        manifest = {
            **revisions,
            "source_root": str(source),
            "rby1_root": str(rby1),
            "bodex_root": str(bodex) if bodex is not None else None,
            "links": counts,
            "sha256": lock["sha256"],
            "generated_aiworker_urdf_sha256": generated_hash,
            "relativized_rby1_usd_sha256": portable_usd_hash,
        }
        (work / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
        (work / "env.sh").write_text(env_text(output, bodex))
        work.rename(output)
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True,
                        help="Research SimVLA checkout with kitchen, Anubis, and AI Worker assets")
    parser.add_argument("--rby1-root", type=Path,
                        default=Path(os.environ["SIMVLA_RBY1M_DIR"]) if "SIMVLA_RBY1M_DIR" in os.environ else None,
                        help="Prepared RB-Y1 model tree (or $SIMVLA_RBY1M_DIR)")
    parser.add_argument("--bodex-root", type=Path, help="Extracted BODex root for collection")
    parser.add_argument(
        "--usd-python", type=Path, default=Path(sys.executable),
        help="Python with usd-core==24.11 for making the staged RB-Y1 layer relocatable",
    )
    parser.add_argument("--output", type=Path, default=REPO / "outputs/repro-assets-portable")
    args = parser.parse_args(argv)
    if args.rby1_root is None:
        parser.error("--rby1-root or SIMVLA_RBY1M_DIR is required for all three robots")
    try:
        manifest = stage(
            args.source_root, args.rby1_root, args.output, args.bodex_root, args.usd_python
        )
    except (OSError, ValueError, subprocess.CalledProcessError) as exc:
        parser.error(str(exc))
    print(f"Staged {sum(manifest['links'].values())} linked files at {args.output.resolve()}")
    print(f"Run: source {shlex.quote(str(args.output.resolve() / 'env.sh'))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
